<div class="col-md-3">
    <a class="btn btn-default" href="/usuario">Volver</a>
</div>
<div class="col-md-9">
	<fieldset>
        <legend>Informacion del Usuario</legend>
        <form action="/usuario/save" method="POST" role="form" class="form-horizontal">
            <input type="hidden" name="id" value="" />
            <div class="form-group">
                <label class="col-sm-2 control-label">Nombre</label>
                <div class="col-sm-10">
                    <input class="form-control" name="nombre" value="" />
                </div>
            </div>
            <div class="form-group">
                <label class="col-sm-2 control-label">Apellido paterno</label>
                <div class="col-sm-10">
                    <input class="form-control" name="paterno" value="" />
                </div>
            </div>
            <div class="form-group">
                <label class="col-sm-2 control-label">Apellido materno</label>
                <div class="col-sm-10">
                    <input class="form-control" name="materno" value="" />
                </div>
            </div>
            <input type="submit" value="Guardar" class="btn btn-primary" />
        </form>
    </fieldset>
</div>